# This is a basic workflow to help you get started with Actions

name: BuildRelease

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      # Build latex
      - name: Build
        uses: xu-cheng/latex-action@v4
        with:
          args: -pdf -interaction=nonstopmode -jobname=UNSW_Debating_Society_Constitution
          root_file: main.tex
          os: debian
      # Generate tag
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::As_of_$(date +"%Y.%m.%d_%H-%M")"
      # Deploy built pdf to releases
      - name: Release
        uses: softprops/action-gh-release@v2.3.3
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: UNSW_Debating_Society_Constitution.pdf
